In [1]:
import matplotlib.pyplot as plt
import numpy as np
import sympy as sp
from scipy import linalg as la
sp.init_printing() 
import warnings
warnings.filterwarnings("ignore")



#next line is so that we can use letters with SymPy matrix
sp.var('a, b, c, d, e, f, g, h, i, j, k', real = True)

## Goals and Commands

#### Goals
1. Matrix operations
2. Matrix inverse
3. LU-factorization
4. Determinants

#### Commands
1. Operator @
2. np.linalg.inv, .inv
3. Scipy.linalg library
3. .lu, .lu_factor, .lu_solve
4. .det


### Matrix Multiplication

Matrix multiplication is done the same way as matrix-vector multiplication, using @-symbol.

#### Example

Find AB, where $A=\begin{bmatrix} 1 & 1 & 0 \\ 2 & 5 & -1 \end{bmatrix}$ and $B=\begin{bmatrix} 1 & 1 \\ 2 & 5 \\ 0 & 1 \end{bmatrix}$. 
We will do it using both NumPy and SymPy:

In [2]:
A=np.array([[1,1,0],[2,5,-1]])
B=np.array([[1,1],[2,5],[0,1]])
A@B

array([[ 3,  6],
       [12, 26]])

In [3]:
A=sp.Matrix([[1,1,0],[2,5,-1]])
B=sp.Matrix([[1,1],[2,5],[0,1]])
A@B

⎡3   6 ⎤
⎢      ⎥
⎣12  26⎦

#### End of example

Adding matrices and multiplying them by scalars are straightforward.

In [4]:
A=np.array([[1,2],[3,4]])
B=np.array([[4,3], [-2,0]])
A+2*B

array([[ 9,  8],
       [-1,  4]])

To raise matrix to a power, we can use linalg library if we are using NumPy:

In [5]:
np.linalg.matrix_power(A,2)

array([[ 7, 10],
       [15, 22]])

In SymPy this is a bit simpler: 

In [6]:
A=sp.Matrix([[1,2],[3,4]])
A**2

⎡7   10⎤
⎢      ⎥
⎣15  22⎦

Warning: in NumPy A**2 is not the same as A@A. Instead it squares every entry of the array.

### Inverse

To find the inverse of the matric we can use command `inv` from linalg library if we are using NumPy, or `.inv()` if we are using SymPy.

#### Example:

Find inverse of $A=\begin{bmatrix} 1 & 1 & 4 \\ 2 & 5 & -1 \\ 0 & 2 & 1\end{bmatrix}$ and $B=\begin{bmatrix} a & b\\ c&d\end{bmatrix}$

In [7]:
A=np.array([[1,1,0],[2,5,-1], [0,2,1]])
np.linalg.inv(A)

array([[ 1.4, -0.2, -0.2],
       [-0.4,  0.2,  0.2],
       [ 0.8, -0.4,  0.6]])

In [8]:
A=sp.Matrix([[1,1,0],[2,5,-1], [0,2,1]])
A.inv()

⎡7/5   -1/5  -1/5⎤
⎢                ⎥
⎢-2/5  1/5   1/5 ⎥
⎢                ⎥
⎣4/5   -2/5  3/5 ⎦

In [9]:
B=sp.Matrix([[a,b],[c,d]])
B.inv()

⎡    d         -b    ⎤
⎢─────────  ─────────⎥
⎢a⋅d - b⋅c  a⋅d - b⋅c⎥
⎢                    ⎥
⎢   -c          a    ⎥
⎢─────────  ─────────⎥
⎣a⋅d - b⋅c  a⋅d - b⋅c⎦

Next we introduce a new library -- SciPy.linalg. It is quite similar to numpy.linalg, but it has more commands in it. It works on numpy arrays, so you can use either library. However, some commands that we will need will come only from SciPy. For now, here is an example of finding inverse using SciPy. Reminder: we defined scipy.linalg as la

In [10]:
A=np.array([[1,1,0],[2,5,-1], [0,2,1]])
la.inv(A)

array([[ 1.4, -0.2, -0.2],
       [-0.4,  0.2,  0.2],
       [ 0.8, -0.4,  0.6]])

### LU factorization

To perform LU factorization we need SciPy library.

#### Example

$A = \begin{bmatrix} 1& 2& 3 \\ 1 & 9& 4 \\ 0 & 1 & 4\end{bmatrix}$ Find LU-decoomposition of A

In [11]:
A=np.array([[1,2,3],[1,9,4],[0,1,4]])
P, L, U = la.lu(A)
print(P)
print(L)
print(U)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1.         0.         0.        ]
 [1.         1.         0.        ]
 [0.         0.14285714 1.        ]]
[[1.         2.         3.        ]
 [0.         7.         1.        ]
 [0.         0.         3.85714286]]


#### End of example

As you can see, `la.lu` returns three matrices. L and U matricies are the lower and upper triangualar matrices that we were looking for. However, we also get matrix P. This is permutaion matrix and in fact, A=PLU. In this particualr case P is just identity and so it is not important, but in general it can swap some of the rows of A, so that LU factorization works out.

If we need to actually solve linear systems using LU factorization, it is better to use `lu_factor` and `lu_solve` commands from scipy.linalg.

`lu_factor` will perform LU factorization and return a matrix that combines lower part of L ignoring 1's from the main diagonal and upper part of U. It also returns a vector piv that holds information on which rows were swapped (more precisely, row i was interchanged with row piv[i])

`lu_solve` then will use result of `lu_factor` to actually solve the system.

#### Example

Solve Solve $A {\bf {x}} = {\bf{b}}$ using LU factorization, were $A=\begin{bmatrix} 2&-2&4 \\ 1&-3&1\\ 3&7&5 \end{bmatrix}$ and ${\bf{b}}=\begin{bmatrix} 0\\-5\\7\end{bmatrix}$



In [12]:
A=np.array([[2,-2,4],[1,-3,1],[3,7,5]])
b=np.array([0,-5,7])

lu,piv=la.lu_factor(A)
x=la.lu_solve((lu, piv), b)
x

array([-5.,  1.,  3.])

To make it a bit more clear what lu matrix is that is being returned by `lu_factor`, compare it to L and U matricies: 

In [13]:
P, L, U = la.lu(A)
sp.Matrix(L),sp.Matrix(U),sp.Matrix(lu)

⎛⎡       1.0          0    0 ⎤  ⎡3.0         7.0                5.0       ⎤  ⎡
⎜⎢                           ⎥  ⎢                                         ⎥  ⎢
⎜⎢0.666666666666667  1.0   0 ⎥, ⎢ 0   -6.66666666666667  0.666666666666667⎥, ⎢
⎜⎢                           ⎥  ⎢                                         ⎥  ⎢
⎝⎣0.333333333333333  0.8  1.0⎦  ⎣ 0           0                -1.2       ⎦  ⎣

       3.0                7.0                5.0       ⎤⎞
                                                       ⎥⎟
0.666666666666667  -6.66666666666667  0.666666666666667⎥⎟
                                                       ⎥⎟
0.333333333333333         0.8               -1.2       ⎦⎠

In [14]:
P, piv  

(array([[0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]]),
 array([2, 2, 2], dtype=int32))

Notice, piv is [2,2,2]. So if you start with identity matrix and then perform the following three swaps you will get matrix P:
1.  Swap row 1 with row 2
2.  Swap row 2 with row 2 (does nothing)
3.  Swap row 3 with row 2

#### End of example

In our last example, we will solve a large linear system in two different ways: directly solving it, and then solving it with LU factorization. We will also time each attempt to see which one is faster. 



#### Example

Let $A$ be a big matrix given below:


In [15]:
A=np.array([[4,-1,-1,0,0,0,0,3],[4,5,0,1,0,0,0,0],[4,0,4,-1,3,0,0,0],[0,4,3,4,0,-1,0,0],[0,0,4,0,4,3,-1,0],[0,0,0,3,-1,4,0,-1],[0,0,0,0,4,0,4,-1],[0,0,0,0,0,4,-1,4]])
sp.Matrix(A)

⎡4  -1  -1  0   0   0   0   3 ⎤
⎢                             ⎥
⎢4  5   0   1   0   0   0   0 ⎥
⎢                             ⎥
⎢4  0   4   -1  3   0   0   0 ⎥
⎢                             ⎥
⎢0  4   3   4   0   -1  0   0 ⎥
⎢                             ⎥
⎢0  0   4   0   4   3   -1  0 ⎥
⎢                             ⎥
⎢0  0   0   3   -1  4   0   -1⎥
⎢                             ⎥
⎢0  0   0   0   4   0   4   -1⎥
⎢                             ⎥
⎣0  0   0   0   0   4   -1  4 ⎦

Let ${\bf b}=(5,10,0,-10,5,5,0,5)$. Let's solve $A{\bf x}={\bf b}$

In [16]:
b=np.array([5,10,0,-10,5,5,0,5])

In [17]:
np.linalg.solve(A,b)

array([ 1.5044607 ,  0.82749993, -3.64689762, -0.15534241,  2.80480176,
        1.74793721, -3.1245718 , -1.27908016])

In [18]:
lu, piv = la.lu_factor(A)
la.lu_solve((lu, piv), b)

array([ 1.5044607 ,  0.82749993, -3.64689762, -0.15534241,  2.80480176,
        1.74793721, -3.1245718 , -1.27908016])

So the answers are the same, which is good. Now lets find average execution time. We will do 40 runs, each consisting of 100 loops of each cell, and then find the average time of execution of a run.

In [19]:
%%timeit -n 100 -r 40 
np.linalg.solve(A,b)


12.1 µs ± 1.42 µs per loop (mean ± std. dev. of 40 runs, 100 loops each)


In [20]:
%%timeit -n 100 -r 40
lu, piv = la.lu_factor(A)
la.lu_solve((lu, piv), b)


8.7 µs ± 2.5 µs per loop (mean ± std. dev. of 40 runs, 100 loops each)


As you can see LU factorization method executes faster. For larger systems, time difference will increase.

### Determinants

There are of course commands to find determinant of the matrix directly. In SymPy it is `.det()` and in NumPy and SciPy its `.linalg.det`.

#### Example

Find determinant of $A=\begin{bmatrix} 2&-2&4 \\ 1&-3&1\\ 3&7&5 \end{bmatrix}$

#### Solution

In [21]:
A=np.array([[2,-2,4],[1,-3,1],[3,7,5]])
np.linalg.det(A)

In [22]:
B=sp.Matrix(A)
B.det()

#### End of Example
