In [1]:
import matplotlib.pyplot as plt
import numpy as np
import sympy as sp
from scipy import linalg as la
sp.init_printing() 
import warnings
warnings.filterwarnings("ignore")


## Goals and Commands

#### Goals
1. Vector subspaces for a given matrix
2. Basis and coordinate vectors

#### Commands
1. columnspace(), rowspace(), nullspace()
2. la.null_space(A)


The easiest way to get Null, Column and Row spaces of a matrix in Jupyter, is to use SymPy library. It already has all needed commands:

In [2]:
A=sp.Matrix([[1,1,2],[2,5,0],[4,7,4]])
A

⎡1  1  2⎤
⎢       ⎥
⎢2  5  0⎥
⎢       ⎥
⎣4  7  4⎦

In [3]:
A.rref()    ## Let's check the pivot positions

⎛⎡1  0  10/3⎤        ⎞
⎜⎢          ⎥        ⎟
⎜⎢0  1  -4/3⎥, (0, 1)⎟
⎜⎢          ⎥        ⎟
⎝⎣0  0   0  ⎦        ⎠

In [4]:
A.columnspace()

⎡⎡1⎤  ⎡1⎤⎤
⎢⎢ ⎥  ⎢ ⎥⎥
⎢⎢2⎥, ⎢5⎥⎥
⎢⎢ ⎥  ⎢ ⎥⎥
⎣⎣4⎦  ⎣7⎦⎦

In [5]:
A.rowspace()

[[1  1  2], [0  3  -4]]

In [6]:
A.nullspace()

⎡⎡-10/3⎤⎤
⎢⎢     ⎥⎥
⎢⎢ 4/3 ⎥⎥
⎢⎢     ⎥⎥
⎣⎣  1  ⎦⎦

As you can see, you get a list of vectors that form a basis of a given vector subspace.

It is a possible to use SciPy.linalg library as well. Null space is easy:


In [7]:
A=np.array([[1,1,2],[2,5,0],[4,7,4]])
la.null_space(A)

array([[-0.89442719],
       [ 0.35777088],
       [ 0.26832816]])

#### Note: la.null_space is a very good way to solve homogeneous equation that has non-trivial solutions.

#### Example

Let $A=\begin{bmatrix} 1 & 1 &-2 & 3 \\ 2 & 2 &-4 & 6\\-2 & -2 & 4 & -6 \end{bmatrix}$. Solve $A{\bf x}={\bf 0}$.

#### Solution

In [8]:
A=np.array([[1,1,-2,3],[2,2,-4,6],[-2,-2,4,-6]])
la.null_space(A)

array([[ 9.50380788e-01, -1.73521441e-01,  3.28938236e-16],
       [-3.48120940e-03,  3.65131777e-01, -8.94427191e-01],
       [ 6.96241879e-03, -7.30263554e-01, -4.47213595e-01],
       [-3.10991580e-01, -5.50712481e-01,  4.17348070e-16]])

#### End of Example

There isn't a direct way to find Column and Row spaces using SciPy, so instead we have to use something called QR-factorization which we will discuss later. 

All questions on finding dimension of the vector subspace or determining whether a set of vectors forms basis for a vector subspace or finding coordinate vector of some vector given a basis. etc are easily solved using techniques we already have. Here is a small example dealing with some of these questions:

#### Example

Let $\bf{a_1}=\begin{bmatrix} 1 \\ 2 \\ 1 \end{bmatrix}$, $\bf{a_2}=\begin{bmatrix} -1 \\ 3 \\ 2 \end{bmatrix}$ and $\bf{a_3}=\begin{bmatrix} 4 \\ 5 \\ 5 \end{bmatrix}$. Let $\bf{b}=\begin{bmatrix} 1 \\ -5 \\ 2 \end{bmatrix}$.

1. Check that a set $\mathcal{A}=\{\bf{a_1},\bf{a_2},\bf{a_3}\}$ form a basis for $\mathbb{R}^3$.
2. Find $\mathcal{A}$-coordinate vector of $\bf{b}$

#### Solution
1. 
While this is not necessary, I will write each vector as a row of the matrix and then take transpose. This is useful trick if you have hard time writing array with given column vectors

In [9]:
At=sp.Matrix([[1,2,1],[-1,3,2],[4,5,5]])
A=At.T
A.rref()

⎛⎡1  0  0⎤           ⎞
⎜⎢       ⎥           ⎟
⎜⎢0  1  0⎥, (0, 1, 2)⎟
⎜⎢       ⎥           ⎟
⎝⎣0  0  1⎦           ⎠

We have 3 linearly independent vectors in $\mathbb{R}^3$, and so we have a basis for $\mathbb{R}^3$.

2.
Now for a coordinate vector, we just need to solve a matrix equation:

In [10]:
b=sp.Matrix([1,-5,2])
A.solve(b)

⎡-47/7⎤
⎢     ⎥
⎢-2/7 ⎥
⎢     ⎥
⎣13/7 ⎦

#### End of Example