In [2]:
import matplotlib.pyplot as plt
import numpy as np
import sympy as sp
from scipy import linalg as la
sp.init_printing() 
import warnings
warnings.filterwarnings("ignore")


## Goals and Commands

#### Goals
1. Outer product
2. Spectral decomposition


#### Commands
1. np.outer

It will be useful here to introduce a new type of vector products. An outer product of two vectors ${\bf u}$ and ${\bf v}$ is defined to be ${\bf u} \otimes {\bf v} = {\bf u} \cdot {\bf v}^T$. Note that the outer product of two vectors in $\mathbb{R}^n$ is an $n \times n$ matrix

In [3]:
u=np.array([1,2,3])
v=np.array([-1,3,5])
np.outer(u,v)

array([[-1,  3,  5],
       [-2,  6, 10],
       [-3,  9, 15]])

A useful rule: outer product of vector with itself is a symmetric matrix:

In [4]:
np.outer(v,v)

array([[ 1, -3, -5],
       [-3,  9, 15],
       [-5, 15, 25]])

In [5]:
np.outer(u,u)

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

#### Example

Perform Spectral Decomposition and check the result for $A=\begin{bmatrix} 1 & 1 & 2 \\ 1 & 5 & 0 \\ 2 & 0 & 4 \end{bmatrix}$

#### Solution

In [15]:
A=np.array([[1,1,2],[1,5,0],[2,0,4]])
D, P = np.linalg.eig(A); P

# Recall that P contains normalized eigenvectors.

array([[ 0.88765034, -0.39711255,  0.23319198],
       [-0.17214786, -0.75578934, -0.63178128],
       [-0.42713229, -0.52065737,  0.73923874]])

In [16]:
D

array([-0.15632517,  5.52542756,  4.63089761])

In [17]:
P0=np.outer(P[:,0], P[:,0]); P0

array([[ 0.78792312, -0.15280711, -0.37914412],
       [-0.15280711,  0.02963489,  0.07352991],
       [-0.37914412,  0.07352991,  0.18244199]])

In [18]:
P1=np.outer(P[:,1], P[:,1]); P1

array([[0.15769838, 0.30013343, 0.20675958],
       [0.30013343, 0.57121753, 0.39350729],
       [0.20675958, 0.39350729, 0.2710841 ]])

In [19]:
P2=np.outer(P[:,2], P[:,2]); P2

array([[ 0.0543785 , -0.14732633,  0.17238454],
       [-0.14732633,  0.39914759, -0.4670372 ],
       [ 0.17238454, -0.4670372 ,  0.54647391]])

In [20]:
# Lets check our decomposition

np.round(D[0]*P0+D[1]*P1+D[2]*P2)

array([[1., 1., 2.],
       [1., 5., 0.],
       [2., 0., 4.]])

#### End of solution


Notice that $P0$ is much smaller eigenvalue than the other two, so lets remove the term from the decomposition with that eigenvalue and see what we get:

In [22]:
np.round(D[1]*P1+D[2]*P2)

array([[1., 1., 2.],
       [1., 5., 0.],
       [2., 0., 4.]])

As you can see, it looks the same. In reality, it is not exactly the same, but it is very close to the original matrix. We dont see the difference because we round it off.